log:
 format: plain
 level: info
 output: stderr
p2p:
  listen_address: "/ip4/0.0.0.0/tcp/3000"
  public_address: "/ip4/__PUBLIC_IP__/tcp/3000"
  #private_id: __NODE_PRIVATE_ID__
  topics_of_interest:
    messages: "high"
    blocks: "high"
  trusted_peers:
   - address: "/ip4/3.115.194.22/tcp/3000"
     id: ed25519_pk1npsal4j9p9nlfs0fsmfjyga9uqk5gcslyuvxy6pexxr0j34j83rsf98wl2
   - address: "/ip4/13.113.10.64/tcp/3000"
     id: ed25519_pk16pw2st5wgx4558c6temj8tzv0pqc37qqjpy53fstdyzwxaypveys3qcpfl
   - address: "/ip4/52.57.214.174/tcp/3000"
     id: ed25519_pk1v4cj0edgmp8f2m5gex85jglrs2ruvu4z7xgy8fvhr0ma2lmyhtyszxtejz
   - address: "/ip4/3.120.96.93/tcp/3000"
     id: ed25519_pk10gmg0zkxpuzkghxc39n3a646pdru6xc24rch987cgw7zq5pmytmszjdmvh
   - address: "/ip4/52.28.134.8/tcp/3000"
     id: ed25519_pk1unu66eej6h6uxv4j4e9crfarnm6jknmtx9eknvq5vzsqpq6a9vxqr78xrw
   #- address: "/ip4/13.52.208.132/tcp/3000"
     #id: ed25519_pk15ppd5xlg6tylamskqkxh4rzum26w9acph8gzg86w4dd9a88qpjms26g5q9
   - address: "/ip4/54.153.19.202/tcp/3000"
     id: ed25519_pk1j9nj2u0amlg28k27pw24hre0vtyp3ge0xhq6h9mxwqeur48u463s0crpfk
rest:
 listen: 0.0.0.0:3101
storage: "./storage"